spring.application.name=transferpath

spring.datasource.url=jdbc:postgresql://localhost:5432/transferpath
spring.datasource.username=adityarajiv
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
